// Luo src/vendor/resvg-wasm.js: base64-inline WASM + pieni init
import { readFile, writeFile } from "node:fs/promises";
const wasm = await readFile("./third_party/resvg/index_bg.wasm"); // vendoroitu
const b64 = Buffer.from(wasm).toString("base64");

const out = `// AUTOGENERATED (do not edit)
const b64 = "${b64}";
let mod, inst;
export async function initResvg() {
  if (inst) return inst;
  const bytes = Uint8Array.from(atob(b64), c => c.charCodeAt(0)).buffer;
  mod = await WebAssembly.compile(bytes);
  // Resvg JS-API:t riippuvat alkuperäisestä wrapperista; käytämme pientä shimmiä:
  // Tuodaan minimalisti: alloc/free + render-funktio modulista (vakiovienti).
  // Jos käytät virallista JS-wrapperia, muokkaa tämän mukaan.
  inst = await WebAssembly.instantiate(mod, { env: {} });
  return inst;
}
export function wasmBytes() {
  return Uint8Array.from(atob(b64), c => c.charCodeAt(0));
}
`;
await writeFile("./src/vendor/resvg-wasm.js", out);
console.log("OK: src/vendor/resvg-wasm.js");
