export default html`
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="28"
    height="24"
    viewBox="0 0 28 24"
    fill="none"
  >
    <line
      y1="1.5"
      x2="28"
      y2="1.5"
      stroke="var(--contentColor)"
      stroke-opacity="0.6"
      stroke-width="3"
    />
    <line
      y1="11.5"
      x2="28"
      y2="11.5"
      stroke="var(--contentColor)"
      stroke-opacity="0.6"
      stroke-width="3"
    />
    <line
      y1="22.5"
      x2="28"
      y2="22.5"
      stroke="var(--contentColor)"
      stroke-opacity="0.6"
      stroke-width="3"
    />
  </svg>
`;
